### ISSUE TITLE
Swap the position of legend and icons?

### ISSUE THREAD

**Issue by Folyd** [lukaslueg/macro_railroad_ext#13]
There are some huge macros, such as [tracing::info!()](https://docs.rs/tracing/latest/tracing/macro.info.html), the diagram fulfills the width. And the icon options are hidden due to overflow. Maybe we should swap the position of legend and icons?

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/3369694/184159948-fc0fa8d6-9d1c-4c21-bb96-1f10c6e80a3f.png">

**Comment by lukaslueg** [comment]
Good catch. Switching the icons would be a clutch. I'm unsure about the CSS: Maybe we can right-aligned-anchor the `railroad_dropdown_content` div to the right side of the `railroad_container` div?

**Comment by Folyd** [comment]
I have no idea. CSS is so hard for me. Maybe we can also move the icons to the top left?

**Comment by lukaslueg** [comment]
This should be fixed by 2983b74, and the exact placement is now tested as well

<img width="694" alt="Bildschirmfoto 2022-08-12 um 18 19 43" src="https://user-images.githubusercontent.com/3148704/184400205-4c4b6d32-5bce-447f-8949-67fc3a523728.png">

**Comment by Folyd** [comment]
Wow! This is great!
