### ISSUE TITLE
`style` attribute -- a quick hint

### ISSUE THREAD

**Issue by h-h-h-h** [lukaslueg/macro_railroad_ext#5]
Wrong:

- https://github.com/lukaslueg/macro_railroad_ext/blob/master/extension/content_scripts/main.js#L56

Explanation:

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style#Setting_styles

**Comment by lukaslueg** [comment]
Thanks for the heads-up. My non-existent knowledge of JS // DOM // CSS // whatever is showing. I guess `.style.width = "100px"` is valid ?

**Comment by h-h-h-h** [comment]
That's correct.

**Comment by lukaslueg** [comment]
As a matter of fact a JS linter complains a lot about the module.
I did not really got around to fixing any of it, since, well, JS will be JS.
